Added devcontainer and debug in devcontainer

diff --git a/contrib/dev-util/cluster b/contrib/dev-util/cluster
--- a/contrib/dev-util/cluster
+++ b/contrib/dev-util/cluster
@@ -1,5 +1,7 @@
 #!/bin/bash
 
+set -x
+
 export PATH=$PATH:/opt/bb/bin
 
 dir=$HOME/.local/share/comdb2-util
@@ -335,25 +337,35 @@ function do_docker {
 }
 
 function tmux_int {
-	/usr/bin/tmux new-window
-	/usr/bin/tmux send-keys "printf '"'\033]2;%s\033\\'"' ${prefix}1" Enter
-	/usr/bin/tmux send-keys "${HOME}/bin/cluster c 1" Enter
+    if ! TMUX=$(command -v tmux); then
+        echo "a tmux installation not found."
+        exit 1
+    fi
+	$TMUX new-window
+	$TMUX send-keys "printf '"'\033]2;%s\033\\'"' ${prefix}1" Enter
+	$TMUX send-keys "${HOME}/bin/cluster c 1" Enter
 	n=$(get clusternum)
 	for ((i=2;i<=$n;++i)); do
-		/usr/bin/tmux split-window
-		/usr/bin/tmux send-keys "printf '"'\033]2;%s\033\\'"' ${prefix}${i}" Enter
-		/usr/bin/tmux send-keys "$HOME/bin/cluster c ${i}" Enter
-		/usr/bin/tmux select-layout tiled
+		$TMUX split-window
+		$TMUX send-keys "printf '"'\033]2;%s\033\\'"' ${prefix}${i}" Enter
+#		$TMUX send-keys "$HOME/bin/cluster c ${i}" Enter
+        $TMUX send-keys "$PWD/cluster c ${i}" Enter
+		$TMUX select-layout tiled
 	done
 }
 
 function sync_panes {
-	/usr/bin/tmux set-window-option synchronize-panes
-	/usr/bin/tmux set-option window-status-style "bg=colour124"
-	/usr/bin/tmux set-option pane-active-border-style "fg=colour124"
+    if ! TMUX=$(command -v tmux); then
+        echo "a tmux installation not found."
+        exit 1
+    fi
+
+	$TMUX set-window-option synchronize-panes
+	$TMUX set-option window-status-style "bg=colour124"
+	$TMUX set-option pane-active-border-style "fg=colour124"
 }
 
-function tmux {
+function open_tmux {
 	tmux_int
 	sync_panes
 }
@@ -584,7 +596,7 @@ elif [[ "$1" == "rm" ]] || [[ "$1" == "stop" ]] || [[ "$1" == "kill" ]] || [[ "$
     fi
 elif [[ "$1" == "tmux" ]]; then
     check-containers-ready || exit 1
-	tmux
+	open_tmux
 elif [[ "$1" == "db" ]]; then
     check-containers-ready || exit 1
 	db ${2:-${defaultdb}}
